[tool.poetry]
name = "empire-bc-security-fork"
version = "5.6.4"
description = ""
authors = ["BC Security <info@bc-security.org>"]
readme = "README.md"
homepage = "https://github.com/BC-SECURITY/Empire"
repository = "https://github.com/BC-SECURITY/Empire.git"
packages = [
    { include = "empire.py" },
    { include = "empire/server/**/*.py" },
    { include = "empire/client/**/*.py" },
]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
urllib3 = "^2.0.3"
requests = "^2.31.0"
iptools = "^0.7.0"
macholib = "^1.16.2"
dropbox = "^11.36.2"
pyOpenSSL = "^23.2.0"
zlib_wrapper = "^0.1.3"
netifaces = "^0.11.0"
jinja2 = "^3.1.2"
xlutils = "^2.0.0"
pyparsing = "^3.1.0"
PyMySQL = "^1.1.0"
SQLAlchemy = "^2.0.18"
PyYAML = "^6.0.1"
SQLAlchemy-Utc = "^0.14.0"
prompt-toolkit = "^3.0.39"
terminaltables = "^3.1.10"
docopt = "^0.6.2"
humanize = "^4.7.0"
pycryptodome = "^3.18.0"
cryptography = "^41.0.1"
fastapi = "^0.99.1"
uvicorn = "^0.22.0"
jq = "^1.4.1"
aiofiles = "^23.1.0"
python-multipart = "^0.0.6"
python-jose = {version = "^3.3.0", extras = ["cryptography"]}
passlib = {version = "^1.7.4", extras = ["bcrypt"]}
websockify = "^0.10.0"
websockets = "^11.0.3"
pyperclip = "^1.8.2"
pyvnc = {git = "https://github.com/BC-SECURITY/pyVNC.git"}
python-socketio = {extras = ["client"], version = "^5.8.0"}
Flask = "^2.3.2"
pysecretsocks = {git = "https://github.com/BC-SECURITY/PySecretSOCKS.git"}
donut-shellcode = "^1.0.2"
python-obfuscator = "^0.0.2"
pyinstaller = "^5.13.0"
md2pdf = "^1.0.1"
tabulate = "^0.9.0"
stix2 = "^3.0.1"


[tool.poetry.group.dev.dependencies]
httpx = "^0.24.1" # For starlette TestClient
isort = "^5.12.0"
black = "^23.7.0"
pytest = "^7.4.0"
pytest-timeout = "^2.1.0"
ruff = "^0.0.283"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
supported_extensions = ['pxd', 'py', 'pyi', 'pyx', 'plugin']

[tool.black]
extend-exclude = '''
    (empire/server/data*)
    | (empire/server/downloads*)
    | (empire/client/generated-stagers*)
    | (empire/client/downloads*)
'''
force-exclude = '''
    (empire/server/data*)
    | (empire/server/downloads*)
    | (empire/client/generated-stagers*)
    | (empire/client/downloads*)
'''

#include = '.*\.(plugin)$'

[tool.ruff]
extend-exclude = [
    'empire/server/data',
    'empire/server/downloads',
    'empire/server/common/malleable',
    'empire/client/generated-stagers',
    'empire/client/downloads'
]
# Will revisit line lengths later. Black won't format the strings and comments
# by default. And the experimental flag still has some issues.
# fixes right now: https://github.com/psf/black/issues/2188
extend-ignore = ["E501"]
