[tool.poetry]
name = "empire-bc-security-fork"
version = "5.0.0-alpha1"
description = ""
authors = ["BC Security <info@bc-security.org>"]
readme = "README.md"
homepage = "https://github.com/BC-SECURITY/Empire"
repository = "https://github.com/BC-SECURITY/Empire.git"
packages = [
    { include = "empire.py" },
    { include = "empire/server/**/*.py" },
    { include = "empire/client/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.8"
urllib3 = "*"
requests = "^2.24.0"
iptools = "*"
macholib = "*"
dropbox = "*"
pyOpenSSL = "*"
pyinstaller = "*"
zlib_wrapper = "*"
netifaces = "*"
jinja2 = "*"
xlutils = "*"
pyparsing = "*"
PyMySQL = "^0.10.1"
SQLAlchemy = "^1.3.20"
PyYAML = "^5.3.1"
SQLAlchemy-Utc = "^0.11.0"
prompt-toolkit = "^3.0.9"
terminaltables = "^3.1.0"
docopt = "^0.6.2"
humanize = "^3.2.0"
pydantic = "^1.8.1"
pycryptodome = "^3.10.1"
cryptography = "^3.4.7"
fastapi = "0.70"
uvicorn = "^0.14.0"
jq = "^1.2.1"
aiofiles = "^0.7.0"
python-multipart = "^0.0.5"
python-jose = {version = "^3.3.0", extras = ["cryptography"]}
passlib = {version = "^1.7.4", extras = ["bcrypt"]}
websockify = "^0.10.0"
websockets = "^10.1"
tk = "^0.1.0"
pyperclip = "^1.8.2"
pyvnc = {git = "https://github.com/BC-SECURITY/pyVNC.git"}
python-socketio = "^5.5.1"
Flask = "^2.1.2"
# Donut breaks with Python 3.10 and hasn't been updated since 2019.
# See https://github.com/TheWover/donut/issues/107 for more detail
# The BC-SECURITY fork brings in the changes from S4ntiagoP's pull request
# https://github.com/TheWover/donut/pull/101
donut-shellcode = {git = "https://github.com/BC-SECURITY/donut.git"}

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
isort = "^5.10.1"
black = "^22.1.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
supported_extensions = ['pxd', 'py', 'pyi', 'pyx', 'plugin']

[tool.black]
extend-exclude = '''
    (empire/server/data*)
    | (empire/server/downloads*)
    | (empire/client/generated-stagers*)
    | (empire/client/downloads*)
'''
#include = '.*\.(plugin)$'
